// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:hypixel_tracker/data/models/auction_model.dart';
import 'package:hypixel_tracker/data/models/bazaar_item_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AuctionModelAdapter());
    registerAdapter(BazaarItemModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AuctionModelAdapter());
    registerAdapter(BazaarItemModelAdapter());
  }
}
